apiVersion: v1
kind: Service
metadata:
  name: redis_auction
spec:
  selector:
    app: redis_auction
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
