apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
  labels:
    app: postgres-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres-user
          image: kaustubhduse/postgres_user:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-user-secret
          volumeMounts:
            - name: postgres-user-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-user-storage
          persistentVolumeClaim:
            claimName: postgres-user-pvc
