apiVersion: v1
kind: Service
metadata:
  name: rabbitmq_auction
spec:
  selector:
    app: rabbitmq_auction
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
  type: LoadBalancer
