apiVersion: v1
kind: Service
metadata:
  name: redis_live-score
spec:
  selector:
    app: redis_live-score
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
