apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  labels:
    app: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata: 
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres-auth
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-auth-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-auth-pvc
