apiVersion: v1
kind: Service
metadata:
  name: mongo-payment
spec:
  selector:
    app: mongo-payment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
