apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: kaustubhduse/user-service:2
          ports:
            - containerPort: 5002
          envFrom:
            - secretRef:
                name: user-secrets
