apiVersion: v1
kind: Service
metadata:
  name: live-score-service
spec:
  selector:
    app: live-score-service
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
  type: LoadBalancer
